/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Login.Login;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;


public class ViewAndSearchProductDetails extends javax.swing.JFrame {

    /**
     * Creates new form ViewProductDetails
     */
    public ViewAndSearchProductDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbPcategory = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPproducts = new javax.swing.JTable();
        btnPviewProducts = new javax.swing.JButton();
        btnPclear = new javax.swing.JButton();
        btnPlogout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View and Search products");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GREEN GLAMOUR COSMETIC STORE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search by Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, -1));

        txtPname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 90, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search by Price");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        txtPprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtPprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 90, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search by Catetgory");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        cmbPcategory.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbPcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SkinCareProduct", "HairCareProduct", "Makeup", "FragranceProduct", "PersonalCareProduct" }));
        cmbPcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, -1, -1));

        tblPproducts.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblPproducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Category", "Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblPproducts);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 520, 175));

        btnPviewProducts.setText("View All Products");
        btnPviewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPviewProductsActionPerformed(evt);
            }
        });
        getContentPane().add(btnPviewProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        btnPclear.setText("Clear");
        btnPclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnPclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        btnPlogout.setText("Logout");
        btnPlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 2, 36)); // NOI18N
        jLabel7.setText("G&G");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/03t.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPnameActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) tblPproducts.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tblModel);
        tblPproducts.setRowSorter(sorter);

        // Get the text to be searched from the Search field
        String searchText = txtPname.getText().trim();

        if (searchText.isEmpty()) {
            // If the search text is empty, show an error message and return
            JOptionPane.showMessageDialog(this, "Please enter something to search.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                // Use RowFilter to perform case-insensitive regex filtering
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
            } catch (java.util.regex.PatternSyntaxException ex) {
                // Handle regex pattern syntax errors, if any
                JOptionPane.showMessageDialog(this, "Invalid search pattern.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_txtPnameActionPerformed

    private void txtPpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPpriceActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) tblPproducts.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tblModel);
        tblPproducts.setRowSorter(sorter);

        // Get the text to be searched from the Search field
        String searchText = txtPprice.getText().trim();

        if (searchText.isEmpty()) {
            // If the search text is empty, show an error message and return
            JOptionPane.showMessageDialog(this, "Please enter something to search.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                // Use RowFilter to perform case-insensitive regex filtering
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
            } catch (java.util.regex.PatternSyntaxException ex) {
                // Handle regex pattern syntax errors, if any
                JOptionPane.showMessageDialog(this, "Invalid search pattern.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtPpriceActionPerformed

    private void btnPviewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPviewProductsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblPproducts.getModel();
        model.setRowCount(0);
        
        String filepath = "Products.txt";
        File file = new File(filepath);
        try{
            BufferedReader br = new BufferedReader(new FileReader(file));
            
            
            
            String line;
            while((line = br.readLine()) != null){
                String[] dataRow = line.split(" ");
                model.addRow(dataRow);
                
            }
            br.close();
            
        }catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "File not found: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error reading file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPviewProductsActionPerformed

    private void btnPlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlogoutActionPerformed
        // TODO add your handling code here:
        Login L = new Login();
        this.dispose();
        L.setVisible(true);
    }//GEN-LAST:event_btnPlogoutActionPerformed

    private void btnPclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPclearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblPproducts.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnPclearActionPerformed
  
    private void cmbPcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPcategoryActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) tblPproducts.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tblModel);
        tblPproducts.setRowSorter(sorter);

        // Get the text to be searched from the Search field
        String searchText = cmbPcategory.getSelectedItem().toString();

        if (searchText.isEmpty()) {
            // If the search text is empty, show an error message and return
            JOptionPane.showMessageDialog(this, "Please enter something to search.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                // Use RowFilter to perform case-insensitive regex filtering
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
            } catch (java.util.regex.PatternSyntaxException ex) {
                // Handle regex pattern syntax errors, if any
                JOptionPane.showMessageDialog(this, "Invalid search pattern.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmbPcategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAndSearchProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAndSearchProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAndSearchProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAndSearchProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAndSearchProductDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPclear;
    private javax.swing.JButton btnPlogout;
    private javax.swing.JButton btnPviewProducts;
    private javax.swing.JComboBox<String> cmbPcategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPproducts;
    private javax.swing.JTextField txtPname;
    private javax.swing.JTextField txtPprice;
    // End of variables declaration//GEN-END:variables
}
