public class Cashier extends javax.swing.JFrame {

    /**
     * Creates new form Cashier
     */
    public Cashier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCusername = new javax.swing.JTextField();
        rdoCshowpass = new javax.swing.JRadioButton();
        btnCback = new javax.swing.JButton();
        btnClogin = new javax.swing.JButton();
        Cpassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashier Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 80, 28));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtCusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtCusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 190, 30));

        rdoCshowpass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rdoCshowpass.setText("Show Password");
        rdoCshowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCshowpassActionPerformed(evt);
            }
        });
        getContentPane().add(rdoCshowpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        btnCback.setText("Back");
        btnCback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnCback, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        btnClogin.setText("Login");
        btnClogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnClogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        Cpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 190, 30));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 2, 36)); // NOI18N
        jLabel7.setText("G&G");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/02.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusernameActionPerformed

    private void btnCbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCbackActionPerformed
        // TODO add your handling code here:
        Login L = new Login();
        this.dispose();
        L.setVisible(true);
    }//GEN-LAST:event_btnCbackActionPerformed

    private void CpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CpasswordActionPerformed

    private void rdoCshowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCshowpassActionPerformed
        // TODO add your handling code here:
        if(rdoCshowpass.isSelected()){
            Cpassword.setEchoChar((char)0);
        }else{
            Cpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_rdoCshowpassActionPerformed

    private void btnCloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloginActionPerformed
        // TODO add your handling code here:
        String Username = txtCusername.getText();
        String Password = new String(Cpassword.getPassword());
        
        if(Username.isEmpty() || Password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill the required fields");
        }else {
            try {
                BufferedReader reader = new BufferedReader(new FileReader("Cashier.txt"));
                String line;
                boolean found = false;
                
                while ((line = reader.readLine()) != null) {
                    if (line.contains("Username: " + Username) && reader.readLine().contains("Password: " + Password)) {
                        found = true;
                        break;
                    }
                }

                reader.close();
                
                if (found) {
                    JOptionPane.showMessageDialog(this, "Login successful!");
                    ViewAndSearchProductDetails GUI = new ViewAndSearchProductDetails();
                    this.dispose();
                    GUI.setVisible(true);

                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid username or password. Please try again.");
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error reading data from file: " + ex.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
            }
    }//GEN-LAST:event_btnCloginActionPerformed

    private void clearFields(){
        txtCusername.setText("");
        Cpassword.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Cpassword;
    private javax.swing.JButton btnCback;
    private javax.swing.JButton btnClogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rdoCshowpass;
    private javax.swing.JTextField txtCusername;
    // End of variables declaration//GEN-END:variables
}
