public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMusername = new javax.swing.JTextField();
        rdoMshowpass = new javax.swing.JRadioButton();
        btnMback = new javax.swing.JButton();
        btnMlogin = new javax.swing.JButton();
        Mpassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtMusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtMusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 190, 30));

        rdoMshowpass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rdoMshowpass.setText("Show Password");
        rdoMshowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMshowpassActionPerformed(evt);
            }
        });
        getContentPane().add(rdoMshowpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        btnMback.setText("Back");
        btnMback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnMback, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        btnMlogin.setText("Login");
        btnMlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnMlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        Mpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Mpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 190, 30));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 2, 36)); // NOI18N
        jLabel7.setText("G&G");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/02.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMusernameActionPerformed

    private void rdoMshowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMshowpassActionPerformed
        // TODO add your handling code here:
        if(rdoMshowpass.isSelected()) {
            Mpassword.setEchoChar((char)0);
        }else{
            Mpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_rdoMshowpassActionPerformed

    private void btnMloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMloginActionPerformed
        // TODO add your handling code here:
        String Username = txtMusername.getText();
        String Password = new String (Mpassword.getPassword());
        
        if (Username.isEmpty() || Password.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please fill the required fields");
        }else {
            try {
                BufferedReader reader = new BufferedReader(new FileReader("Manager.txt"));
                String line;
                boolean found = false;

                while ((line = reader.readLine()) != null) {
                    if (line.contains("Username: " + Username) && reader.readLine().contains("Password: " + Password)) {
                        found = true;
                        break;
                    }
                }

                reader.close();

                if (found) {
                    JOptionPane.showMessageDialog(this, "Login successful!");
                    ManagerUI UI=new ManagerUI();
                    this.dispose();
                    UI.setVisible(true);

                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid username or password. Please try again.");
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error reading data from file: " + ex.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnMloginActionPerformed
  
    private void clearFields(){
        txtMusername.setText("");
        Mpassword.setText("");
    }
    
    private void btnMbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMbackActionPerformed
        // TODO add your handling code here:
        Login L = new Login();
        this.dispose();
        L.setVisible(true);
    }//GEN-LAST:event_btnMbackActionPerformed

    private void MpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Mpassword;
    private javax.swing.JButton btnMback;
    private javax.swing.JButton btnMlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rdoMshowpass;
    private javax.swing.JTextField txtMusername;
    // End of variables declaration//GEN-END:variables
}
