public class AddProducts extends javax.swing.JFrame {
    
    productsDB pdb= new productsDB();

    /**
     * Creates new form AddProducts
     */
    public AddProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAproductID = new javax.swing.JTextField();
        txtAname = new javax.swing.JTextField();
        txtAprice = new javax.swing.JTextField();
        cmbAcategory = new javax.swing.JComboBox<>();
        btnAddback = new javax.swing.JButton();
        btnAddupdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Product");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Products");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 194, 130, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Product Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 245, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Product Category");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 140, -1, -1));
        getContentPane().add(txtAproductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 87, 150, -1));
        getContentPane().add(txtAname, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 191, 150, -1));
        getContentPane().add(txtAprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 242, 150, -1));

        cmbAcategory.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbAcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SkinCareProduct", "HairCareProduct", "Makeup", "FragranceProduct", "PersonalCareProduct" }));
        getContentPane().add(cmbAcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 137, 150, -1));

        btnAddback.setText("Back");
        btnAddback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddback, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        btnAddupdate.setText("Update");
        btnAddupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 2, 36)); // NOI18N
        jLabel7.setText("G&G");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/03t.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddupdateActionPerformed
        // TODO add your handling code here:
        if(txtAproductID.getText().trim().isEmpty() || cmbAcategory.getSelectedItem().toString().isEmpty() || txtAname.getText().trim().isEmpty() ||
                txtAprice.getText().trim().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Please fill in all required fields","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
String productID = txtAproductID.getText().trim();
String productCategory = cmbAcategory.getSelectedItem().toString();
String productName = txtAname.getText().trim();
String productPrice = txtAprice.getText().trim();

products p1 = new products(productID, productCategory, productName, productPrice) {
    @Override
    protected void displayInformation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
};
String dataLine = productID + "," + productCategory + "," + productName + "," + productPrice;
saveDataToFile(dataLine);

if (pdb.add(p1)) {
    JOptionPane.showMessageDialog(this, "Report Added");
} else {
    JOptionPane.showMessageDialog(this, "Report can't be added");
}
    }//GEN-LAST:event_btnAddupdateActionPerformed

    private void btnAddbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddbackActionPerformed
        // TODO add your handling code here:
        ManagerUI UI = new ManagerUI();
        this.dispose();
        UI.setVisible(true);
    }//GEN-LAST:event_btnAddbackActionPerformed

    private void saveDataToFile(String dataLine) {
    String productID = txtAproductID.getText();
    String productCategory = cmbAcategory.getSelectedItem().toString();
    String productName = txtAname.getText();
    String productPrice = txtAprice.getText();
    
    try {
        String fileName = "Products.txt"; // File name without full path
        FileWriter Writer = new FileWriter(fileName, true);
        Writer.write( productID + " " + productCategory + " " + productName + " " + productPrice);
        Writer.write(System.getProperty("line.separator"));
        Writer.close();
        JOptionPane.showMessageDialog(null, "Successful");
        setVisible(true);
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error saving data to file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
 }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddback;
    private javax.swing.JButton btnAddupdate;
    private javax.swing.JComboBox<String> cmbAcategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAname;
    private javax.swing.JTextField txtAprice;
    private javax.swing.JTextField txtAproductID;
    // End of variables declaration//GEN-END:variables
}
