public class CreateNewAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateNewAccount
     */
    public CreateNewAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNAusername = new javax.swing.JTextField();
        rdoNAshowpass = new javax.swing.JRadioButton();
        btnNAback = new javax.swing.JButton();
        btnNAcreate = new javax.swing.JButton();
        NApassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create New Account");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create New Account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 6, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));
        getContentPane().add(txtNAusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 150, 30));

        rdoNAshowpass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rdoNAshowpass.setText("Show Password");
        rdoNAshowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNAshowpassActionPerformed(evt);
            }
        });
        getContentPane().add(rdoNAshowpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        btnNAback.setText("Back");
        btnNAback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNAbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnNAback, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        btnNAcreate.setText("Create");
        btnNAcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNAcreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnNAcreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));
        getContentPane().add(NApassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 150, 30));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 2, 36)); // NOI18N
        jLabel2.setText("G&G");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/03t.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdoNAshowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNAshowpassActionPerformed
        // TODO add your handling code here:
        if(rdoNAshowpass.isSelected()){
            NApassword.setEchoChar((char)0);
        }else{
            NApassword.setEchoChar('*');
        }
    }//GEN-LAST:event_rdoNAshowpassActionPerformed

    private void btnNAcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNAcreateActionPerformed
        // TODO add your handling code here:
        String Username = txtNAusername.getText();
        String Password = new String(NApassword.getPassword());

        if (Username.isEmpty() || Password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill the required fields");
        } else {
            registerUser(Username, Password);
        }
    }//GEN-LAST:event_btnNAcreateActionPerformed

    private void btnNAbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNAbackActionPerformed
        // TODO add your handling code here:
        ManagerUI UI = new ManagerUI();
        this.dispose();
        UI.setVisible(true);
    }//GEN-LAST:event_btnNAbackActionPerformed

     private void registerUser(String Username, String Password) {
        try {
            FileWriter writer = new FileWriter("Cashier.txt", true);
             writer.write("Username: "  +  Username  + "\n");
                writer.write("Password: "  +  Password  + "\n");
            writer.write(System.lineSeparator());
            writer.close();
            JOptionPane.showMessageDialog(this, "Registration successful!");
            clearFields();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error saving data to file: " + ex.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
 private void clearFields() {
        txtNAusername.setText("");
        NApassword.setText("");
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField NApassword;
    private javax.swing.JButton btnNAback;
    private javax.swing.JButton btnNAcreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rdoNAshowpass;
    private javax.swing.JTextField txtNAusername;
    // End of variables declaration//GEN-END:variables
}
